### ISSUE TITLE
Randomly [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by Abade002** [adafruit/Adafruit_CCS811_python#1]
Hi, I have two MCP9808 and one CCS811 collecting data on a raspberry. But randomly the program crashes and give the following error:

Traceback (most recent call last):
  File "button.py", line 116, in <module>
    if ccs.available():
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_CCS811/Adafruit_CCS811.py", line 122, in available
    self._status.set(self._device.readU8(CCS811_STATUS))
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 149, in readU8
  File "build/bdist.linux-armv7l/egg/Adafruit_PureIO/smbus.py", line 155, in read_byte_data
IOError: [Errno 121] Remote I/O error

Anyone know the cause of this error? I read in the page "This sensor is not well supported on Raspberry Pi." but i already stretched the line.

**Comment by Abade002** [comment]
`import time 
import RPi.GPIO as GPIO
import MySQLdb as mdb
import sys
import time
import array
import PCF8591 as ADC
import smbus
#import tsl2591
from Adafruit_CCS811 import Adafruit_CCS811
import Adafruit_MCP9808.MCP9808 as MCP9808

ADC.setup(0x48)

bbin = 23
bbout = 24
nump = 0
led3 = 17
led2 = 27
led1 = 22
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(bbin,GPIO.IN)
GPIO.setup(bbout,GPIO.IN)
GPIO.setup(led1,GPIO.OUT)
GPIO.setup(led2,GPIO.OUT)
GPIO.setup(led3,GPIO.OUT)
GPIO.output(led1, GPIO.LOW)
GPIO.output(led2, GPIO.LOW)
GPIO.output(led3, GPIO.LOW)

previn=0
prevout=0

                     
ccs =  Adafruit_CCS811()
while not ccs.available():
	pass
tempccs = ccs.calculateTemperature()
ccs.tempOffset = tempccs - 25.0
mcpout = MCP9808.MCP9808()
mcpin = MCP9808.MCP9808(address=0x19)

#tsl = tsl2591.Tsl2591()  # initialize
go1 = True
go2 = True       
tempoutbuff1 = []
tempinbuff1 = []
co2buff1 = []
vocbuff1 = []
tempinbuff2 = []
tempoutbuff2 = [] 
co2buff2 = []
vocbuff2 = []
tempinaux = 0
tempoutaux = 0 
vocaux = 0
co2aux = 0
tin = 0
tout = 0
voc = 0
co2 = 0

print "Wait...\n";

while True:
	#take a reading
	biin = GPIO.input(bbin)
	bout = GPIO.input(bbout)
	
	#if the last reading was low and this one high, print
	if (biin != previn and nump < 5):
		nump = nump + 1
		time.sleep(0.20)
		previn = GPIO.input(bbin)

	if (bout!= prevout and nump > 0):
		nump = nump - 1
		time.sleep(0.20)
		prevout = GPIO.input(bbout)
	
	if nump == 0:
		GPIO.output(led1, GPIO.LOW)
		GPIO.output(led2, GPIO.LOW)
		GPIO.output(led3, GPIO.LOW)
	elif nump == 1:
		GPIO.output(led1, GPIO.HIGH)
		GPIO.output(led2, GPIO.LOW)
		GPIO.output(led3, GPIO.LOW)
	elif nump == 2:
		GPIO.output(led1, GPIO.LOW)
		GPIO.output(led2, GPIO.HIGH)
		GPIO.output(led3, GPIO.LOW)
	elif nump == 3:
		GPIO.output(led1, GPIO.HIGH)
		GPIO.output(led2, GPIO.HIGH)
		GPIO.output(led3, GPIO.LOW)
	elif nump == 4:
		GPIO.output(led1, GPIO.LOW)
		GPIO.output(led2, GPIO.LOW)
		GPIO.output(led3, GPIO.HIGH)
	elif nump == 5:
		GPIO.output(led1, GPIO.HIGH)
		GPIO.output(led2, GPIO.LOW)
		GPIO.output(led3, GPIO.HIGH)
		
	
	timetup = time.gmtime()
	seconds = time.strftime('%S', timetup)
	
	if (int(seconds)%10 == 0 or int(seconds) == 0):
		if go1 == True:
			for i in range (0,10):
				tempinbuff1.append(mcpin.readTempC())
				tempoutbuff1.append(mcpout.readTempC())
				if ccs.available():
					temp = ccs.calculateTemperature()
					if not ccs.readData():
						co2buff1.append(ccs.geteCO2())
						vocbuff1.append(ccs.getTVOC())
					else:
						print "<<\n<<\nCCS811 ERROR\n<<\n<<";
			for i in range (0,10):
				tempinaux = tempinbuff1[i] + tempinaux
				tempoutaux = tempoutbuff1[i] + tempoutaux
				
			for i in xrange(len(co2buff1)):
				co2aux = co2aux + co2buff1[i]
				vocaux = vocaux + vocbuff1[i]
			tempoutaux=tempoutaux/10
			tempinaux=tempinaux/10
			co2aux = co2aux/len(co2buff1)
			vocaux = vocaux/len(co2buff1)
			tempinbuff2.append(tempinaux)
			tempoutbuff2.append(tempoutaux)
			co2buff2.append(co2aux)
			vocbuff2.append(vocaux)
			go1 = False
	else:
		go1 = True
		tempinaux=0
		tempoutaux =0
		co2aux = 0
		vocaux = 0
		tempinbuff1 = []
		tempoutbuff1 = []
		vocbuff1 = []
		co2buff1 = []
		
	if (int(seconds) == 0):
		if go2 == True:
			for i in xrange(len(tempinbuff2)):
				tin = tin + tempinbuff2[i]
				tout = tout + tempoutbuff2[i]
			for i in xrange(len(co2buff2)):
				voc = voc + vocbuff2[i]
				co2 = co2 + co2buff2[i]
			tin = tin/len(tempinbuff2)
			tout = tout/len(tempoutbuff2)
			co2 = co2/len(co2buff2)
			voc = voc/len(vocbuff2)
			go2 = False
			tempinbuff2 = []
			tempoutbuff2 = []
			co2buff2 = []
			vocbuff2 = []
			
			#voiceValue = ADC.read(3)
			#print 'Value:', voiceValue
			
			date = time.strftime('%Y-%m-%d %H:%M:%S', timetup)
			print ">>", date
			print "Tempin:", tin, "Tempout:", tout, "CO2:", co2, "VOC:", voc, "NP:", nump
			sql = "INSERT INTO node1 values ('" + date +  "', " + str(tin) +  ", " + str(tout) +  ", " + str(co2) +  ", " + str(voc) +  ", " + str(nump) + ", 0);"
			print sql, "\n"
			# Open database connection
			db = mdb.connect("10.3.1.130", "root", "tfraz1md", "thesis2") 

			# prepare a cursor object using cursor() method
			cursor = db.cursor()
			
			try:
				# Execute the SQL command
				cursor.execute(sql)
				# Commit your changes in the database
				db.commit()
			except:
				# Rollback in case there is any error
				db.rollback()



	else:
		go2 = True
		tin = 0
		tout=0
		voc = 0
		co2 = 0
`

**Comment by Abade002** [comment]
`timetup = time.gmtime()
	seconds = time.strftime('"%S", timetup)
	
	if (int(seconds)%10 == 0 or int(seconds) == 0):
		if go1 == True:
			for i in range (0,10):
				tempinbuff1.append(mcpin.readTempC())
				tempoutbuff1.append(mcpout.readTempC())
				if ccs.available():
					temp = ccs.calculateTemperature()
					if not ccs.readData():
						co2buff1.append(ccs.geteCO2())
						vocbuff1.append(ccs.getTVOC())
					else:
						print "<<\n<<\nCCS811 ERROR\n<<\n<<";
			for i in range (0,10):
				tempinaux = tempinbuff1[i] + tempinaux
				tempoutaux = tempoutbuff1[i] + tempoutaux
				
			for i in xrange(len(co2buff1)):
				co2aux = co2aux + co2buff1[i]
				vocaux = vocaux + vocbuff1[i]
			tempoutaux=tempoutaux/10
			tempinaux=tempinaux/10
			co2aux = co2aux/len(co2buff1)
			vocaux = vocaux/len(co2buff1)
			tempinbuff2.append(tempinaux)
			tempoutbuff2.append(tempoutaux)
			co2buff2.append(co2aux)
			vocbuff2.append(vocaux)
			go1 = False
	else:
		go1 = True
		tempinaux=0
		tempoutaux =0
		co2aux = 0
		vocaux = 0
		tempinbuff1 = []
		tempoutbuff1 = []
		vocbuff1 = []
		co2buff1 = []`

**Comment by muthu29** [comment]
Hi have you solved it ? Got the same problem

**Comment by Abade002** [comment]
No in Python. I made the port of this library to C++. I have sometimes outliers but I can clean easily with a few lines of code.

**Comment by ladyada** [comment]
ccs811 is really picky with the clock stretching - we do our best by slowing down I2C a *lot* but also check out the SGP30 which is more stable!
